/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import dao.DAO_DiaChi;
import entity.NhanVien;
import java.time.Clock;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import dao.DAO_NhanVien;
import entity.DiaChi;
import java.awt.List;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author phoai
 */

import javax.swing.table.DefaultTableModel;

public class Form_NhanVien extends javax.swing.JPanel {

    private dao.DAO_DiaChi daoDiaChi = new DAO_DiaChi();
    private Vector<String> vecQuanHuyen;
    private Vector<String> vecPhuongXa;
    private Vector<String> vecTinhTP = new Vector<String>();
    private DAO_NhanVien daoNV = new DAO_NhanVien();
    private DefaultTableModel modelNV = new DefaultTableModel();

    /**
     * Creates new form Form_NhanVien
     */
    public Form_NhanVien(){
        initComponents();
        loadTinh();
        try {
            loadDS();
        } catch (Exception ex) {
            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaNV.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        cbbTrangThai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnThoiViec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbbDCTinhTP = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbbLoaiNV = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbbDCQuanHuyen = new javax.swing.JComboBox<>();
        cbbDCPhuongXa = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnXoaRong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("SĐT: ");

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNV.setMinimumSize(new java.awt.Dimension(64, 35));
        txtMaNV.setPreferredSize(new java.awt.Dimension(64, 35));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giới tính: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Trạng thái: ");

        cbbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.setPreferredSize(new java.awt.Dimension(78, 33));

        cbbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm", "Đã nghỉ" }));
        cbbTrangThai.setPreferredSize(new java.awt.Dimension(78, 33));
        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 102, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icon_them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 102, 102));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/ion_sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 102, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/error.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 102));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/ion_chuyenPhong.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(0, 102, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/search.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThoiViec.setBackground(new java.awt.Color(255, 102, 102));
        btnThoiViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoiViec.setForeground(new java.awt.Color(255, 255, 255));
        btnThoiViec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/huyPhongCho.png"))); // NOI18N
        btnThoiViec.setText("Thôi việc");
        btnThoiViec.setPreferredSize(new java.awt.Dimension(133, 40));
        btnThoiViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiViecActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên nhân viên: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("CMND/CCCD:");

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tỉnh/Thành Phố:");

        cbbDCTinhTP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbDCTinhTP.setMinimumSize(new java.awt.Dimension(78, 33));
        cbbDCTinhTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDCTinhTPActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Loại nhân viên:");

        cbbLoaiNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbLoaiNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Lý" }));
        cbbLoaiNV.setToolTipText("");
        cbbLoaiNV.setMinimumSize(new java.awt.Dimension(78, 33));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Quận/Huyện:");

        cbbDCQuanHuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbDCQuanHuyen.setMinimumSize(new java.awt.Dimension(78, 33));
        cbbDCQuanHuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDCQuanHuyenActionPerformed(evt);
            }
        });

        cbbDCPhuongXa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbDCPhuongXa.setMinimumSize(new java.awt.Dimension(78, 33));
        cbbDCPhuongXa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDCPhuongXaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Phường/Xã:");

        btnXoaRong.setBackground(new java.awt.Color(0, 102, 102));
        btnXoaRong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaRong.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaRong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/search.png"))); // NOI18N
        btnXoaRong.setText("Xóa Rỗng");
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbLoaiNV, 0, 104, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtCMND))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbGioiTinh, 0, 177, Short.MAX_VALUE)
                            .addComponent(cbbDCTinhTP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbDCQuanHuyen, 0, 211, Short.MAX_VALUE)
                            .addComponent(cbbDCPhuongXa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(btnXoaRong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoiViec, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenNV)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbDCTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbDCQuanHuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDCPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoaiNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbbGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThoiViec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaRong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính", "SĐT", "Trạng thái", "Loại nhân viên", "CMND", "Tỉnh/TP", "Quận/Huyện", "Phường/Xã"
            }
        ));
        tableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhanVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void getQuanTheoThanhPho() {
        vecQuanHuyen = daoDiaChi.getAllHuyenTheoTinh(cbbDCTinhTP.getSelectedItem().toString());
        DefaultComboBoxModel<String> mdQuanHuyen = new DefaultComboBoxModel<>(vecQuanHuyen);
        cbbDCQuanHuyen.setModel(mdQuanHuyen);
    }

    private void getPhuongXaTheoQuanHuyen() {
        vecPhuongXa = daoDiaChi.getAllPhuongXaTheoTinhVaHuyen(cbbDCTinhTP.getSelectedItem().toString(), cbbDCQuanHuyen.getSelectedItem().toString());
        DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
        cbbDCPhuongXa.setModel(mdPhuong);
    }

    private void loadDS() throws Exception {
        while (tableNhanVien.getRowCount() > 0) {
            modelNV.removeRow(0);
        }
        modelNV = (DefaultTableModel) tableNhanVien.getModel();
        for (NhanVien nv : daoNV.getDSNhanVien()) {
            modelNV.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.isGioiTinh() == true ? "Nam" : "Nữ",
                nv.getSdt(),
                nv.isTrangThaiLam() == true ? "Đang làm" : "Đã nghỉ",
                nv.isLoaiNhanVien() == true ? "Quản Lý" : "Nhân Viên",
                nv.getCmnd(),
                nv.getDiaChi().getTinhTP(),
                nv.getDiaChi().getQuanHuyen(),
                nv.getDiaChi().getPhuongXa()
            });
        }
    }

    private void loadTinh() {
        vecTinhTP = daoDiaChi.getAllTinh();
        if (vecTinhTP.size() == 1) {
            JOptionPane.showMessageDialog(null, "Lỗi khi đọc danh sách tỉnh!");
            return;
        }
        DefaultComboBoxModel<String> md = new DefaultComboBoxModel<String>(vecTinhTP);
        cbbDCTinhTP.setModel(md);
    }

    private boolean regEx() {
        String ten = "^([A-ZĐÂÁƯ]{1}[a-zvxyỳọáầảấờễàạằệếýộậốũứĩõúữịỗìềểẩớặòùồợãụủíỹắẫựỉỏừỷởóéửỵẳẹèẽổẵẻỡơôưăêâđ]+)((\\s{1}[A-ZĐÂÁƯ][{1}a-vxyỳọáầảấờễàạằệếýộậốũứĩõúữịỗìềểẩớặòùồợãụủíỹắẫựỉỏừỷởóéửỵẳẹèẽổẵẻỡơôưăêâđ]+){1,})$";
        String ten2 = "^([A-ZĐÂÁƯ]{1}[A-ZVXYỲỌÁẦẢẤỜỄÀẠẰỆẾÝỘẬỐŨỨĨÕÚỮỊỖÌỀỂẨỚẶÒÙỒỢÃỤỦÍỸẮẪỰỈỎỪỶỞÓÉỬỴẲẸÈẼỔẴẺỠƠÔƯĂÊÂĐ]+)((\\s{1}[A-ZĐÂÁƯ][{1}A-VXYỲỌÁẦẢẤỜỄÀẠẰỆẾÝỘẬỐŨỨĨÕÚỮỊỖÌỀỂẨỚẶÒÙỒỢÃỤỦÍỸẮẪỰỈỎỪỶỞÓÉỬỴẲẸÈẼỔẴẺỠƠÔƯĂÊÂĐ]+){1,})$";
        String rgten = ten + "|" + ten2;
        String sdt = "^0[3|5|7|8|9]+[0-9]{8}$";
        String cmnd = "[0-9]{9}";

        if (!txtTenNV.getText().matches(rgten)) {
            JOptionPane.showMessageDialog(this, "Tên phải viết hoa chữ cái đầu tiên:\n"
                    + "VD: Nguyễn Đình Thanh \n"
                    + "Hoặc viết hoa hết tất cả:\n"
                    + "VD: NGUYỄN ĐÌNH THANH.");
            return false;
        }
        if (!txtSDT.getText().matches(sdt)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải nhập đúng 10 chữ số!");
            return false;
        }
        if (!txtCMND.getText().matches(cmnd)) {
            JOptionPane.showMessageDialog(this, "CMND phải chứa đúng 9 chữ số!");
            return false;
        }
        if (cbbDCPhuongXa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn địa chỉ");
            return false;
        }
        return true;
    }
    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTrangThaiActionPerformed

    private void cbbDCPhuongXaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDCPhuongXaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDCPhuongXaActionPerformed

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaRongActionPerformed
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtCMND.setText("");
        txtSDT.setText("");
        cbbDCTinhTP.setSelectedIndex(0);
    }//GEN-LAST:event_btnXoaRongActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed

        if (true) {

            while (tableNhanVien.getRowCount() > 0) {
                modelNV.removeRow(0);
            }
            try {
                for (NhanVien nv : daoNV.timNVTheoTenVaSdt(txtTenNV.getText(), txtSDT.getText().toString())) {
                    modelNV.addRow(new Object[]{
                        nv.getMaNV(),
                        nv.getTenNV(),
                        nv.isGioiTinh() == true ? "Nam" : "Nữ",
                        nv.getSdt(),
                        nv.isTrangThaiLam() == true ? "Đang làm" : "Đã nghỉ",
                        nv.isLoaiNhanVien() == true ? "Quản Lý" : "Nhân Viên",
                        nv.getCmnd(),
                        nv.getDiaChi().getTinhTP(),
                        nv.getDiaChi().getQuanHuyen(),
                        nv.getDiaChi().getPhuongXa()
                    });
                }
            } catch (Exception ex) {
                Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (regEx()) {//regex
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm nhân viên ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                try {
                    NhanVien nv = new NhanVien(
                            daoNV.sinhMaTuDong(),
                            txtTenNV.getText(),
                            cbbGioiTinh.getSelectedItem().toString().equalsIgnoreCase("Nam"),
                            txtSDT.getText(),
                            "123",
                            cbbTrangThai.getSelectedItem().toString().equalsIgnoreCase("Đang làm"),
                            cbbLoaiNV.getSelectedItem().toString().equalsIgnoreCase("Nhân viên"),
                            txtCMND.getText(),
                            new DiaChi(cbbDCTinhTP.getSelectedItem().toString(), cbbDCQuanHuyen.getSelectedItem().toString(), cbbDCPhuongXa.getSelectedItem().toString()));
                    if (daoNV.timNhanVien(txtSDT.getText().trim()) == null) {
                        daoNV.themNV(nv);
                        JOptionPane.showMessageDialog(this, "Thêm thành công!");
                        btnLamMoiActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (tableNhanVien.getSelectedRow() > -1) {
            if (regEx()) {
                int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa nhân viên ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (option == 0) {
                    try {
                        NhanVien nv1 = new NhanVien();
                        nv1.setMaNV(txtMaNV.getText());
                        nv1.setTenNV(txtTenNV.getText());
                        nv1.setGioiTinh(cbbGioiTinh.getSelectedItem().toString().equalsIgnoreCase("Nam"));
                        nv1.setSdt(txtSDT.getText());
                        boolean trangThaiLam = cbbTrangThai.getSelectedItem().toString().trim() == "Đang làm" ? true : false;
                        System.out.print("ttnv" + cbbTrangThai.getSelectedItem().toString());

                        nv1.setTrangThaiLam(trangThaiLam);

                        boolean loaiNV = cbbLoaiNV.getSelectedItem().toString() == "Quản Lý" ? true : false;
                        System.out.print("loainv" + cbbLoaiNV.getSelectedItem().toString());
                        nv1.setLoaiNhanVien(loaiNV);

                        nv1.setCmnd(txtCMND.getText());
                        DiaChi dcNV = new DiaChi(cbbDCTinhTP.getSelectedItem().toString(), cbbDCQuanHuyen.getSelectedItem().toString(), cbbDCPhuongXa.getSelectedItem().toString());
                        nv1.setDiaChi(dcNV);
                        System.out.println(loaiNV);
                        System.out.println(nv1);
                        if (daoNV.capNhatNhanVien(nv1) > 0) {
                            JOptionPane.showMessageDialog(this, "Sửa thành công!");
                            btnLamMoiActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Sửa thất bại");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

            }
        } else
            JOptionPane.showMessageDialog(this, "Nhân viên phải được chọn trên bảng!");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tableNhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên để xoá!");
        } else {
            String sdt = modelNV.getValueAt(row, 3).toString();
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá nhân viên? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                try {
                    if (daoNV.xoaNhanVien(sdt.trim())) {
                        JOptionPane.showMessageDialog(this, "Xoá thành công!");
                        btnLamMoiActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xoá thất bại!");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        try {
            loadDS();
        } catch (Exception ex) {
            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThoiViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiViecActionPerformed
        int row = tableNhanVien.getSelectedRow();
        if (row > -1) {
            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn cho nhân viên: " + modelNV.getValueAt(row, 1) + " thôi việc?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                try {
                    int kt = daoNV.capNhatNhanVienNghiLam(modelNV.getValueAt(row, 0).toString());
                    if (kt > 0) {
                        JOptionPane.showMessageDialog(this, "Thành công !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thất bại !");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnThoiViecActionPerformed

    private void cbbDCTinhTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDCTinhTPActionPerformed
        // TODO add your handling code here:
        vecQuanHuyen = new Vector<String>();
        DefaultComboBoxModel<String> mdQuan = new DefaultComboBoxModel<>(vecQuanHuyen);
        cbbDCQuanHuyen.setModel(mdQuan);
        vecPhuongXa = new Vector<String>();
        vecPhuongXa.add("Phường/Xã");
        DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
        cbbDCPhuongXa.setModel(mdPhuong);
        getQuanTheoThanhPho();
    }//GEN-LAST:event_cbbDCTinhTPActionPerformed

    private void cbbDCQuanHuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDCQuanHuyenActionPerformed
        // TODO add your handling code here:
        getPhuongXaTheoQuanHuyen();
    }//GEN-LAST:event_cbbDCQuanHuyenActionPerformed

    private void tableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhanVienMouseClicked
        // TODO add your handling code here:
        int index = tableNhanVien.getSelectedRow();
        if (index != -1) {
            txtMaNV.setText(modelNV.getValueAt(index, 0).toString());
            txtTenNV.setText(modelNV.getValueAt(index, 1).toString());
            cbbGioiTinh.setSelectedItem(modelNV.getValueAt(index, 2));
            txtSDT.setText(modelNV.getValueAt(index, 3).toString());
            cbbTrangThai.setSelectedItem(modelNV.getValueAt(index, 4).toString());
            cbbLoaiNV.setSelectedItem(modelNV.getValueAt(index, 5).toString());
            txtCMND.setText(modelNV.getValueAt(index, 6).toString());
            cbbDCTinhTP.setSelectedItem(modelNV.getValueAt(index, 7));
            getQuanTheoThanhPho();
            cbbDCQuanHuyen.setSelectedItem(modelNV.getValueAt(index, 8));
            getPhuongXaTheoQuanHuyen();
            cbbDCPhuongXa.setSelectedItem(modelNV.getValueAt(index, 9));
        }
    }//GEN-LAST:event_tableNhanVienMouseClicked

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoiViec;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JComboBox<String> cbbDCPhuongXa;
    private javax.swing.JComboBox<String> cbbDCQuanHuyen;
    private javax.swing.JComboBox<String> cbbDCTinhTP;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<String> cbbLoaiNV;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables

}
