/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import dao.DAO_CT_HoaDonBan;
import dao.DAO_HoaDonBan;
import dao.DAO_KhachHang;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import dao.DAO_Thuoc;
import entity.CT_HoaDonBan;
import entity.CongDung;
import entity.HoaDonBan;
import entity.KhachHang;
import entity.NhanVien;
import entity.Thuoc;
import gui.model.ThemThuocModelTable;
import gui.model.ThuocModelTable;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.awt.Robot;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Form_CuaHang extends javax.swing.JPanel {

    private ArrayList dsDangBaoChe;
    private ArrayList<Thuoc> dst;
    private ArrayList<Thuoc> dsThemThuoc = new ArrayList<>();
    private DAO_Thuoc daot = new DAO_Thuoc();
    private ArrayList dsDonViTinh;
    private ArrayList<String> dsNhomCongDung;
    private ArrayList<String> dsCongDung;
    private ArrayList<Thuoc> dsThuocSearch;
    private DAO_KhachHang daoKH = new DAO_KhachHang();
    private DAO_HoaDonBan daoHDB = new DAO_HoaDonBan();
    private DAO_CT_HoaDonBan daoChiTietBH = new DAO_CT_HoaDonBan();
    private NhanVien nhanVienDangNhap;
    private CT_HoaDonBan chiTietHoaDon;
    private DefaultTableModel modelCuaHangThuoc;
    private DefaultTableModel modelCuaHangThemThuoc;
    private ArrayList<Thuoc> daonew;
    private KhachHang khXuatin;
    private boolean tf_XuatHoaDon = false;
    private ChitietHoadonBanJframe chitiethoadon;

    /**
     * 
     * @param dst 
     */
    private void capNhapModelThuoc(ArrayList<Thuoc> dst) {
        modelCuaHangThuoc = (DefaultTableModel) tableThuoc.getModel();
        for (Thuoc t : dst) {
            modelCuaHangThuoc.addRow(new Object[]{
                t.getTenThuoc(), t.getThanhPhan(), t.getDangBaoChe(), t.getDonViTinh(), t.getHamLuong(), t.getCongDung().getNhomCongDung(),
                t.getHanSuDung(), t.getGiaBan(), t.getSoLuongBanDau()
            }
            );
        }
    }
    /**
     * 
     * @param t 
     */
    private void capNhapModelThemThuoc(Thuoc t) {
        modelCuaHangThemThuoc = (DefaultTableModel) tableGioHang.getModel();

        modelCuaHangThemThuoc.addRow(new Object[]{
            t.getTenThuoc(), t.getHamLuong(), t.getGiaBan(), t.getThueVAT() * 100.0, t.getSoLuongBanDau(), t.tongtien()
        }
        );

    }
    /**
     * 
     * @param ds 
     */
    private void tongTienThanhToan(ArrayList<Thuoc> ds) {
        double tongtien = 0;
        for (Thuoc i : ds) {
            tongtien += i.tongtien();
        }
        if (tongtien == 0) {
            tfTongHoaDon.setText("0 VNĐ"
                    + "");
        } else {
            String x = String.format("%,.0f", tongtien);
            tfTongHoaDon.setText(x + " VNĐ");
        }
    }
    /**
     * 
     * @param nv 
     */
    public Form_CuaHang(NhanVien nv) {
        nhanVienDangNhap = nv;

        initComponents();
        dst = daot.getDsThuoc();
        capNhapModelThuoc(dst);
//        capNhapModelThemThuoc(dsThemThuoc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @throws Exception
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbGioHang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGioHang = new javax.swing.JTable();
        btnThemThuocVaoGioHang = new javax.swing.JButton();
        tfSoLuongCanThem = new javax.swing.JTextField();
        btnXoaThuocKhoiGioHang = new javax.swing.JButton();
        btnChiTietThuoc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTenThuoc = new javax.swing.JTextField();
        tfHoatChat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboDangBC = new javax.swing.JComboBox<>();
        comboDonViTinh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboNhomCD = new javax.swing.JComboBox<>();
        comboCongDung = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lbThongTinHoaDon = new javax.swing.JLabel();
        btThanhToan = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        btnHuyHoaDon = new javax.swing.JButton();
        lbTimSDT = new javax.swing.JLabel();
        tfTimSDT = new javax.swing.JTextField();
        btTimSDT = new javax.swing.JButton();
        lbTenKH = new javax.swing.JLabel();
        lbShowNameKH = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbShowSDT = new javax.swing.JLabel();
        lbTongHoaDon = new javax.swing.JLabel();
        tfTongHoaDon = new javax.swing.JLabel();
        lbTienNhan = new javax.swing.JLabel();
        tfTienNhan = new javax.swing.JTextField();
        lbTienTraLai = new javax.swing.JLabel();
        tfTienTraLai = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Tên Thuốc", "Thành Phần", "Dạng BC", "ĐVT", "Hàm Lượng", "Nhóm Công Dụng", "Hạn Sử Dụng", "Giá(VNĐ)", "Số Lượng"
            }
        ) 
	{
	
	Class[] types = new Class[]{java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class,java.lang.Long.class};
          boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false,false,false};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
}

);

        jScrollPane2.setViewportView(tableThuoc);
        if (tableThuoc.getColumnModel().getColumnCount() > 0) {
            tableThuoc.getColumnModel().getColumn(0).setHeaderValue("Tên Thuốc");
            tableThuoc.getColumnModel().getColumn(1).setHeaderValue("Thành Phần");
            tableThuoc.getColumnModel().getColumn(2).setHeaderValue("Dạng BC");
            tableThuoc.getColumnModel().getColumn(3).setHeaderValue("ĐVT");
            tableThuoc.getColumnModel().getColumn(4).setHeaderValue("Hàm Lượng");
            tableThuoc.getColumnModel().getColumn(5).setHeaderValue("Nhóm Công Dụng");
            tableThuoc.getColumnModel().getColumn(6).setHeaderValue("Hạn Sử Dụng");
            tableThuoc.getColumnModel().getColumn(7).setHeaderValue("Giá(VNĐ)");
            tableThuoc.getColumnModel().getColumn(8).setHeaderValue("Số Lượng");
        }

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/search_30px.png"))); // NOI18N
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/clear_search_30px.png"))); // NOI18N
        btnClear.setText("Xóa Rỗng");
        btnClear.setToolTipText("");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbGioHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGioHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGioHang.setText("Giỏ Hàng");

        tableGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Tên Thuốc", "Hàm Lượng", "Giá(VNĐ)", "VAT", "Số Lượng", "Thành Tiền"
            }
        )
		{
	
	Class[] types = new Class[]{java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Float.class, java.lang.Long.class, java.lang.Double.class};
          boolean[] canEdit = new boolean[]{false, false, false, false, true, false};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
}

);
        jScrollPane1.setViewportView(tableGioHang);
        // dsThemThuoc.add(new Thuoc("Thanh", 100000, "Hello",Float.parseFloat("0.1"), 100));

        btnThemThuocVaoGioHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemThuocVaoGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Add to Shopping Basket_30px.png"))); // NOI18N
        btnThemThuocVaoGioHang.setText("Thêm Thuốc");
        btnThemThuocVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuocVaoGioHangActionPerformed(evt);
            }
        });

        tfSoLuongCanThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfSoLuongCanThem.setText("0");
        tfSoLuongCanThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLuongCanThemActionPerformed(evt);
            }
        });

        btnXoaThuocKhoiGioHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaThuocKhoiGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Clear Shopping Cart_30px.png"))); // NOI18N
        btnXoaThuocKhoiGioHang.setText("Xóa Thuốc");
        btnXoaThuocKhoiGioHang.setMaximumSize(new java.awt.Dimension(139, 37));
        btnXoaThuocKhoiGioHang.setMinimumSize(new java.awt.Dimension(139, 37));
        btnXoaThuocKhoiGioHang.setPreferredSize(new java.awt.Dimension(139, 37));
        btnXoaThuocKhoiGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuocKhoiGioHangActionPerformed(evt);
            }
        });

        btnChiTietThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTietThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/more_details_30px.png"))); // NOI18N
        btnChiTietThuoc.setText("Chi Tiết");
        btnChiTietThuoc.setMaximumSize(new java.awt.Dimension(139, 37));
        btnChiTietThuoc.setMinimumSize(new java.awt.Dimension(139, 37));
        btnChiTietThuoc.setPreferredSize(new java.awt.Dimension(139, 37));
        btnChiTietThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietThuocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnChiTietThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemThuocVaoGioHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSoLuongCanThem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnXoaThuocKhoiGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChiTietThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSoLuongCanThem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaThuocKhoiGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemThuocVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lbGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên Thuốc:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Hoạt chất:");

        tfTenThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTenThuoc.setText("");

        tfHoatChat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfHoatChat.setText("");
        tfHoatChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // tfHoatChatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Dạng BC:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ĐVT:");

        comboDangBC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dsDangBaoChe= daot.getDsDangBaoChe();
        String[] dsbc = new String[dsDangBaoChe.size()];
        for(int i=0; i<dsDangBaoChe.size(); i++)
        {
            dsbc[i]=(String) dsDangBaoChe.get(i);
        }
        comboDangBC.setModel(new javax.swing.DefaultComboBoxModel<>(dsbc));

        comboDonViTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dsDonViTinh= daot.getDsDonViTinh();
        String[] dsdvt = new String[dsDonViTinh.size()];
        for(int i=0; i<dsDonViTinh.size(); i++)
        {
            dsdvt[i]=(String) dsDonViTinh.get(i);
        }
        comboDonViTinh.setModel(new javax.swing.DefaultComboBoxModel<>(dsdvt));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nhóm Công Dụng:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cộng Dụng:");

        comboNhomCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dsNhomCongDung= daot.getDsNhomCongCung();
        String[] dsncd = new String[dsNhomCongDung.size()];
        for(int i=0; i<dsNhomCongDung.size(); i++)
        {
            dsncd[i]=(String) dsNhomCongDung.get(i);
        }
        comboNhomCD.setModel(new javax.swing.DefaultComboBoxModel<>(dsncd));

        comboCongDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dsCongDung= daot.getDsCongCung();
        String[] dscd = new String[dsCongDung.size()];
        for(int i=0; i<dsCongDung.size(); i++)
        {
            dscd[i]=(String) dsCongDung.get(i);
        }
        comboCongDung.setModel(new javax.swing.DefaultComboBoxModel<>(dscd));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTenThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(tfHoatChat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboDangBC, 0, 300, Short.MAX_VALUE)
                    .addComponent(comboDonViTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCongDung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboNhomCD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboDangBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboNhomCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tfHoatChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(comboDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(comboCongDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbThongTinHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbThongTinHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongTinHoaDon.setText("Thông Tin Hóa Đơn");

        btThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/expensive_price_30px.png"))); // NOI18N
        btThanhToan.setText("Thanh Toán");
        btThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThanhToanActionPerformed(evt);
            }
        });

        btnXuatHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/print_30px.png"))); // NOI18N
        btnXuatHoaDon.setText("Xuất/In");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        btnHuyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/cancel_subscription_30px.png"))); // NOI18N
        btnHuyHoaDon.setText("Hủy Hóa Đơn");
        btnHuyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHoaDonActionPerformed(evt);
            }
        });

        lbTimSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTimSDT.setText("Tìm SĐT:");

        tfTimSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTimSDT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfTimSDT.setText("");
        tfTimSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // tfTimSDTActionPerformed(evt);
            }
        });

        btTimSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTimSDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/search_30px.png"))); // NOI18N
        btTimSDT.setText("Tìm");
        btTimSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimSDTActionPerformed(evt);
            }
        });

        lbTenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTenKH.setText("Tên KH:");

        lbShowNameKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbShowNameKH.setText("");

        lbSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSDT.setText("SĐT:");

        lbShowSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbShowSDT.setText("");

        lbTongHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTongHoaDon.setText("Tổng Hóa Đơn(Có VAT):");

        tfTongHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTongHoaDon.setText("0 VNĐ");

        lbTienNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTienNhan.setText("Tiền Nhận:");

        tfTienNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfTienNhan.setForeground(new java.awt.Color(255, 0, 51));
        tfTienNhan.setText("");
        tfTienNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // tfTienNhanActionPerformed(evt);
                // tfTienNhanKeyReleased(evt);
            }
        });

        tfTienNhan.addKeyListener(new java.awt.event.KeyListener()
        {
            /* (non-Javadoc)
             * @see java.awt.event.KeyListener#keyReleased(java.awt.event.KeyEvent)
             */
            @Override
            public void keyReleased(KeyEvent arg0) {
                // TODO Auto-generated method stub
                tfTienNhanKeyReleased(arg0);
            }

            @Override
            public void keyPressed(KeyEvent arg0) {
                // TODO Auto-generated method stub
                
            }

            @Override
            public void keyTyped(KeyEvent arg0) {
                // TODO Auto-generated method stub
                
            }
        });

        lbTienTraLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTienTraLai.setText("Tiền Trả Lại:");

        tfTienTraLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTienTraLai.setText("0 VNĐ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbTenKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbShowNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbShowSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbTongHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTongHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTienTraLai)
                            .addComponent(lbTienNhan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTienNhan)
                            .addComponent(tfTienTraLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(lbTimSDT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTimSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTimSDT))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnHuyHoaDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXuatHoaDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTimSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTimSDT)
                        .addComponent(tfTimSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenKH)
                    .addComponent(lbShowNameKH)
                    .addComponent(lbSDT)
                    .addComponent(lbShowSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongHoaDon)
                    .addComponent(tfTongHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTienNhan)
                    .addComponent(tfTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTienTraLai)
                    .addComponent(tfTienTraLai))
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHuyHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param evt 
     */
    private void btThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThanhToanActionPerformed
        // TODO add your handling code here:
        if (dsThemThuoc.size() == 0) {
            JOptionPane.showMessageDialog(this, "GIỎ HÀNG RỖNG", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String[] tongtien = tfTongHoaDon.getText().split("VNĐ");
                double dbTongTien = DecimalFormat.getNumberInstance().parse(tongtien[0].trim()).doubleValue();
                double dbTienNhan = DecimalFormat.getNumberInstance().parse(tfTienNhan.getText()).doubleValue();
//                System.out.println(tfTienNhan.getText());
                if (dbTienNhan - dbTongTien < 0) {
                    JOptionPane.showMessageDialog(this, "KHÔNG ĐỦ TIỀN THANH TOÁN", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (kiemtraNhapSoDienthoai(tfTimSDT.getText().trim()) == true) {
                        double tienThua = dbTienNhan - dbTongTien;
                        String xTienThua = String.format("%,.0f", tienThua);
                        tfTienTraLai.setText(xTienThua + " VNĐ");
                        KhachHang kh = daoKH.timKhachHangTheoSDT(tfTimSDT.getText().trim());
                        String maKHMua;
                        btTimSDTActionPerformed(evt);
                        if (kh != null) {
                            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xuất hóa đơn và thanh toán luôn không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                            if (option == 0) {
                                tf_XuatHoaDon = true;
                                btnXuatHoaDonActionPerformed(evt);
                                tf_XuatHoaDon = false;
                                maKHMua = kh.getMaKH();
                                HoaDonBan hoaDon = new HoaDonBan();
                                hoaDon.setMaHoaDonBan(daoHDB.taoMaNgauNhien());
                                hoaDon.setKh(kh);
                                hoaDon.setNv(nhanVienDangNhap);
                                daoHDB.taoHoaDon(hoaDon);
                                String maHoaDon = "";
                                for (Thuoc i : dsThemThuoc) {
                                    daot.capNhatSoLuong(i);
                                    daoChiTietBH.capNhatChiTietHoaDon(i, hoaDon.getMaHoaDonBan());
                                }
//                                JOptionPane.showMessageDialog(this, "THANH TOÁN THÀNH CÔNG", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                                dst = daot.getDsThuoc();
                                capNhapModelThuoc(dst);

                                dsThemThuoc = new ArrayList<>();
                                while (tableGioHang.getRowCount() != 0) {
                                    modelCuaHangThemThuoc.removeRow(0);
                                }
                                tongTienThanhToan(dsThemThuoc);
                                refesh();
                                tfTienNhan.setText("");
                                tfTienTraLai.setText("");
                                lbShowNameKH.setText("");
                                lbShowSDT.setText("");
                                tfTimSDT.setText("");
                                tfSoLuongCanThem.setText("0");
                            } else {
                                maKHMua = kh.getMaKH();
                                HoaDonBan hoaDon = new HoaDonBan();
                                hoaDon.setMaHoaDonBan(daoHDB.taoMaNgauNhien());
                                hoaDon.setKh(kh);
                                hoaDon.setNv(nhanVienDangNhap);
                                daoHDB.taoHoaDon(hoaDon);

                                String maHoaDon = "";
                                for (Thuoc i : dsThemThuoc) {
                                    daot.capNhatSoLuong(i);
                                    daoChiTietBH.capNhatChiTietHoaDon(i, hoaDon.getMaHoaDonBan());
                                }
                                JOptionPane.showMessageDialog(this, "THANH TOÁN THÀNH CÔNG", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                                dst = daot.getDsThuoc();
                                capNhapModelThuoc(dst);

                                dsThemThuoc = new ArrayList<>();
                                while (tableGioHang.getRowCount() != 0) {
                                    modelCuaHangThemThuoc.removeRow(0);
                                }
                                tongTienThanhToan(dsThemThuoc);
                                refesh();
                                tfTienNhan.setText("");
                                tfTienTraLai.setText("");
                                lbShowNameKH.setText("");
                                lbShowSDT.setText("");
                                tfTimSDT.setText("");
                                tfSoLuongCanThem.setText("0");
                            }

                        } else {
                            JOptionPane.showMessageDialog(this, "KHÔNG TÌM THẤY KHÁCH HÀNG", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);

                        }
                    }

                }
            } catch (ParseException ex) {
//            Logger.getLogger(Form_CuaHang.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "NHẬP SỐ TIỀN", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);

            }
        }

    }//GEN-LAST:event_btThanhToanActionPerformed

    private void refesh() {
        modelCuaHangThuoc.getDataVector().removeAllElements();
        daonew = daot.getDsThuoc();
        capNhapModelThuoc(daonew);
    }

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        if (dsThemThuoc.size() != 0) {
            if (kiemtraNhapSoDienthoai(tfTimSDT.getText())) {
                btTimSDTActionPerformed(evt);

                if (!tfTienNhan.getText().isEmpty() && kiemTraSoTien()) {
                    try {
//                    double tiennhan = Double.parseDouble(tfTienNhan.getText());
                        double dbTienNhan = DecimalFormat.getNumberInstance().parse(tfTienNhan.getText().trim()).doubleValue();
                        String xtiennhan = String.format("%,.0f", dbTienNhan);
                        chitiethoadon = new ChitietHoadonBanJframe(nhanVienDangNhap, khXuatin, dsThemThuoc, xtiennhan + " VNĐ", tfTienTraLai.getText(), tf_XuatHoaDon);
                        chitiethoadon.setVisible(true);
                        try {
//                            captureFrame(chitiethoadon);

                        } catch (Exception ex) {
                            Logger.getLogger(Form_CuaHang.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } catch (ParseException ex) {
                        Logger.getLogger(Form_CuaHang.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "SỐ TIỀN NHẬN KHÔNG ĐỦ", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "GIỎ HÀNG RỖNG", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void tfHoatChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoatChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoatChatActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Thuoc thuocTim = new Thuoc();
        thuocTim.setTenThuoc(tfTenThuoc.getText());
        thuocTim.setThanhPhan(tfHoatChat.getText());
        thuocTim.setDangBaoChe(comboDangBC.getSelectedItem().toString());
        thuocTim.setDonViTinh(comboDonViTinh.getSelectedItem().toString());
        CongDung cdtim = new CongDung();
        cdtim.setNhomCongDung(comboNhomCD.getSelectedItem().toString());
        cdtim.setCongDung(comboCongDung.getSelectedItem().toString());
        thuocTim.setCongDung(cdtim);

//        dsThuocSearch = daot.timKiemThuoc(tfTenThuoc.getText(), tfHoatChat.getText(), comboDangBC.getSelectedItem().toString(), comboDonViTinh.getSelectedItem().toString(), comboNhomCD.getSelectedItem().toString(), comboCongDung.getSelectedItem().toString());
        dsThuocSearch = daot.timKiemThuocNangCao(thuocTim);
        if (dsThuocSearch.size() == 0) {
            JOptionPane.showMessageDialog(this, "KHÔNG TÌM THẤY THUỐC", "Tìm Thuốc", JOptionPane.ERROR_MESSAGE);
            btnClearActionPerformed(evt);
        } else {
            dst = dsThuocSearch;
//            modelCuaHangThuoc.getDataVector().removeAllElements();
            while (tableThuoc.getRowCount() != 0) {
                modelCuaHangThuoc.removeRow(0);
            }
            capNhapModelThuoc(dst);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfTenThuoc.setText("");
        tfHoatChat.setText("");
        comboCongDung.setSelectedIndex(0);
        comboDangBC.setSelectedIndex(0);
        comboDonViTinh.setSelectedIndex(0);
        comboNhomCD.setSelectedIndex(0);
        dsThuocSearch = null;
        dst = daot.getDsThuoc();
        capNhapModelThuoc(dst);
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfSoLuongCanThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLuongCanThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoLuongCanThemActionPerformed

    private void btnThemThuocVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuocVaoGioHangActionPerformed
        try {
            if (tfSoLuongCanThem.getText().equals("0")) {
                JOptionPane.showMessageDialog(this, "SỐ LƯỢNG PHẢI LỚN HƠN 0", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                int rowSelect = tableThuoc.getSelectedRow();
                if (rowSelect >= 0 && rowSelect < dst.size()) {
                    Thuoc t = dst.get(rowSelect);
                    if (Long.parseLong(tfSoLuongCanThem.getText()) < t.getSoLuongBanDau()) {
                        Thuoc tc = new Thuoc(t.getMaThuoc(), t.getTenThuoc(), t.getGiaBan(), t.getHamLuong(), t.getThueVAT(), Long.parseLong(tfSoLuongCanThem.getText()));
                        tc.setThanhPhan(t.getThanhPhan());
//                        System.out.println(tc.getMaThuoc());
                        if (dsThemThuoc.contains(tc)) {
                            JOptionPane.showMessageDialog(this, "TRÙNG THUỐC", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
                        } else {
                            dsThemThuoc.add(tc);
                            capNhapModelThemThuoc(tc);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "SỐ LƯỢNG MUA PHẢI NHỎ HƠN HOẶC BẰNG SỐ LUỌNG CÓ SẴN", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
                tongTienThanhToan(dsThemThuoc);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "NHẬP SỐ", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemThuocVaoGioHangActionPerformed

    private void btTimSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimSDTActionPerformed

        String sdt = tfTimSDT.getText().trim();
        if (kiemtraNhapSoDienthoai(sdt) == true) {
            KhachHang kh = daoKH.timKhachHangTheoSDT(tfTimSDT.getText().trim());
            if (kh != null) {
                khXuatin = kh;
                lbShowNameKH.setText(kh.getTenKh());
                lbShowSDT.setText(kh.getSdt());
            } else {
                JOptionPane.showMessageDialog(this, "KHÔNG TÌM THẤY KHÁCH HÀNG", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btTimSDTActionPerformed
    private boolean kiemtraNhapSoDienthoai(String sdt) {
        String regexPhoneNumber = "^0[3|5|7|8|9]+[0-9]{8}$";
        Pattern patternPhoneNumber = Pattern.compile(regexPhoneNumber);
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC ĐỂ TRỐNG", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (patternPhoneNumber.matcher(sdt).matches()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "SỐ ĐIỆN THOẠI BẮT ĐẦU TỪ 03,05,07,08,09 VÀ PHẢI ĐỦ 10 SỐ", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void btnXoaThuocKhoiGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuocKhoiGioHangActionPerformed
        // TODO add your handling code here:
        try {
            int index = tableGioHang.getSelectedRow();
            if (index >= 0 && index < dsThemThuoc.size()) {
                // Thuoc t= dsThemThuoc.get(index);
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thuốc này khỏi giỏ hàng", "Xác thực", dialogButton);
                if (dialogResult == 0) {
                    dsThemThuoc.remove(index);
                    modelCuaHangThemThuoc.removeRow(index);
                }
                tongTienThanhToan(dsThemThuoc);
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btnXoaThuocKhoiGioHangActionPerformed

    private void btnHuyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHoaDonActionPerformed
        // TODO add your handling code here:
        dsThemThuoc = new ArrayList<>();
        while (tableGioHang.getRowCount() != 0) {
            modelCuaHangThemThuoc.removeRow(0);
        }
        tfTimSDT.setText("");
        lbTenKH.setText("");
        lbSDT.setText("");
        tfTienNhan.setText("");
        tfTienTraLai.setText("");
        tongTienThanhToan(dsThemThuoc);
    }//GEN-LAST:event_btnHuyHoaDonActionPerformed
    private void setThongBaoMau(JLabel lb, String noiDung, Color mau) {
        lb.setForeground(mau);
        lb.setFont(new Font("Arial", BOLD, 14));
        lb.setText(noiDung);
    }

    private void tfTienNhanKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        String[] tongtien = tfTongHoaDon.getText().split("VNĐ");

        try {
            double dbTongTien = DecimalFormat.getNumberInstance().parse(tongtien[0].trim()).doubleValue();
            double dbTienNhan = DecimalFormat.getNumberInstance().parse(tfTienNhan.getText().trim()).doubleValue();
            tfTienNhan.setText(String.format("%,.0f", dbTienNhan));

            if (dbTienNhan - dbTongTien < 0) {
                setThongBaoMau(tfTienTraLai, "Tiền nhận chưa đủ", Color.RED);
            } else {
                double tienThua = dbTienNhan - dbTongTien;
                String xTienThua = String.format("%,.0f", tienThua);
                tfTienNhan.setForeground(Color.BLUE);
                setThongBaoMau(tfTienTraLai, xTienThua + " VNĐ", Color.BLUE);

            }
        } catch (ParseException ex) {
            setThongBaoMau(tfTienTraLai, "Tiền nhận phải là số", Color.RED);

        }
    }

    private boolean kiemTraSoTien() {
        String[] tongtien = tfTongHoaDon.getText().split("VNĐ");
        try {
            double dbTongTien = DecimalFormat.getNumberInstance().parse(tongtien[0].trim()).doubleValue();
            double dbTienNhan = DecimalFormat.getNumberInstance().parse(tfTienNhan.getText().trim()).doubleValue();
//            System.out.println(dbTienNhan);
            if (dbTienNhan - dbTongTien < 0) {
                return false;
            } else {
                return true;
            }
        } catch (ParseException ex) {
            return false;
        }
    }

    private void btnChiTietThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietThuocActionPerformed
        // TODO add your handling code here:

        int rowSelect = tableThuoc.getSelectedRow();
//        System.out.println(dsThuocSearch != null);
        if (dsThuocSearch != null) {
            if (rowSelect >= 0 && rowSelect < dsThuocSearch.size()) {
                Thuoc t = dsThuocSearch.get(rowSelect);
                new Form_ChiTiet(t.getMaThuoc()).setVisible(true);
            }
        } else if (rowSelect >= 0 && rowSelect < dst.size()) {
            Thuoc t = dst.get(rowSelect);
            new Form_ChiTiet(t.getMaThuoc()).setVisible(true);

        }
    }//GEN-LAST:event_btnChiTietThuocActionPerformed

    private void captureFrame(JFrame frame) throws Exception {
        BufferedImage image = new Robot().createScreenCapture(frame.getBounds());
//        Thread.sleep(4000);
        ImageIO.write(image, "png", new File("src\\xuatfile\\hoadon.png"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTimSDT;
    private javax.swing.JButton btnChiTietThuoc;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHuyHoaDon;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThemThuocVaoGioHang;
    private javax.swing.JButton btnXoaThuocKhoiGioHang;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JComboBox<String> comboCongDung;
    private javax.swing.JComboBox<String> comboDangBC;
    private javax.swing.JComboBox<String> comboDonViTinh;
    private javax.swing.JComboBox<String> comboNhomCD;
    private javax.swing.JButton btThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbTongHoaDon;
    private javax.swing.JLabel tfTongHoaDon;
    private javax.swing.JLabel lbTienTraLai;
    private javax.swing.JLabel tfTienTraLai;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbGioHang;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbShowNameKH;
    private javax.swing.JLabel lbShowSDT;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbThongTinHoaDon;
    private javax.swing.JLabel lbTienNhan;
    private javax.swing.JLabel lbTimSDT;
    private javax.swing.JTable tableGioHang;
    private javax.swing.JTable tableThuoc;
    private javax.swing.JTextField tfHoatChat;
    private javax.swing.JTextField tfSoLuongCanThem;
    private javax.swing.JTextField tfTenThuoc;
    private javax.swing.JTextField tfTienNhan;
    private javax.swing.JTextField tfTimSDT;
    // End of variables declaration//GEN-END:variables

}
