/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import entity.NhanVien;
import javax.swing.JOptionPane;
import dao.DAO_NhanVien;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import java.awt.Font;

public class Form_NhanVien extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DAO_NhanVien daoNV = new DAO_NhanVien();
	private DefaultTableModel modelNV = new DefaultTableModel();

	/**
	 * Creates new form Form_NhanVien
	 */
	public Form_NhanVien() {
		setBackground(new Color(255, 255, 255));
		initComponents();
		try {
			loadDS();
		} catch (Exception ex) {
			Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
		}
		txtMaNV.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtMaNV = new javax.swing.JTextField();
		txtSDT = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		cbbGioiTinh = new javax.swing.JComboBox<>();
		cbbTrangThai = new javax.swing.JComboBox<>();
		btnThem = new javax.swing.JButton();
		btnSua = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		btnLamMoi = new javax.swing.JButton();
		btnTim = new javax.swing.JButton();
		btnThoiViec = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtTenNV = new javax.swing.JTextField();
		txtCMND = new javax.swing.JTextField();
		lableDiaChi = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		cbbLoaiNV = new javax.swing.JComboBox<>();
		btnXoaRong = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableNhanVien = new javax.swing.JTable();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel2.setText("Mã nhân viên:");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel3.setText("SĐT: ");

		txtMaNV.setEditable(false);
		txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtMaNV.setMinimumSize(new java.awt.Dimension(64, 35));
		txtMaNV.setPreferredSize(new java.awt.Dimension(64, 35));
		txtMaNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtMaNVActionPerformed(evt);
			}
		});

		txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel4.setText("Giới tính: ");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel5.setText("Trạng thái: ");

		cbbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
		cbbGioiTinh.setPreferredSize(new java.awt.Dimension(78, 33));

		cbbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm", "Đã nghỉ" }));
		cbbTrangThai.setPreferredSize(new java.awt.Dimension(78, 33));
		cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbbTrangThaiActionPerformed(evt);
			}
		});

		btnThem.setBackground(new Color(43, 123, 255));
		btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnThem.setForeground(new java.awt.Color(255, 255, 255));
		btnThem.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/plus_white.png"))); // NOI18N
		btnThem.setText("Thêm");
		btnThem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThemActionPerformed(evt);
			}
		});

		btnSua.setBackground(new Color(43, 123, 255));
		btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnSua.setForeground(new java.awt.Color(255, 255, 255));
		btnSua.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/edit_white.png"))); // NOI18N
		btnSua.setText("Sửa");
		btnSua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSuaActionPerformed(evt);
			}
		});

		btnXoa.setBackground(new Color(43, 123, 255));
		btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnXoa.setForeground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/bin_white.png"))); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXoaActionPerformed(evt);
			}
		});

		btnLamMoi.setBackground(new Color(43, 123, 255));
		btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
		btnLamMoi.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/reload.png"))); // NOI18N
		btnLamMoi.setText("Làm mới");
		btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLamMoiActionPerformed(evt);
			}
		});

		btnTim.setBackground(new Color(43, 123, 255));
		btnTim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/search_white.png"))); // NOI18N
		btnTim.setText("Tìm");
		btnTim.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTimActionPerformed(evt);
			}
		});

		btnThoiViec.setBackground(new Color(255, 28, 28));
		btnThoiViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnThoiViec.setForeground(new java.awt.Color(255, 255, 255));
		btnThoiViec.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/retire.png"))); // NOI18N
		btnThoiViec.setText("Thôi việc");
		btnThoiViec.setPreferredSize(new java.awt.Dimension(133, 40));
		btnThoiViec.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThoiViecActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel1.setText("Tên nhân viên: ");

		jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel6.setText("CMND/CCCD:");

		txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

		txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

		lableDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		lableDiaChi.setText("Địa chỉ: ");

		jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel9.setText("Loại nhân viên:");

		cbbLoaiNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		cbbLoaiNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Lý" }));
		cbbLoaiNV.setToolTipText("");
		cbbLoaiNV.setMinimumSize(new java.awt.Dimension(78, 33));

		btnXoaRong.setBackground(new Color(43, 123, 255));
		btnXoaRong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnXoaRong.setForeground(new java.awt.Color(255, 255, 255));
		btnXoaRong.setIcon(new ImageIcon(Form_NhanVien.class.getResource("/image/icon/close_white.png"))); // NOI18N
		btnXoaRong.setText("Xóa Rỗng");
		btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXoaRongActionPerformed(evt);
			}
		});

		txtDiaChi = new JTextField();
		txtDiaChi.setFont(new Font("Segoe UI", Font.PLAIN, 14));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel1Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(txtSDT, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtMaNV, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(jPanel1Layout
						.createParallelGroup(Alignment.TRAILING).addComponent(jLabel9).addComponent(jLabel5))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(cbbTrangThai, 0, 104, Short.MAX_VALUE)
								.addPreferredGap(ComponentPlacement.RELATED))
						.addComponent(cbbLoaiNV, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE))
				.addGap(22)
				.addGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING).addComponent(jLabel1).addComponent(lableDiaChi))
				.addGap(4)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(Alignment.LEADING,
								jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(btnXoaRong)
												.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnTim)
												.addPreferredGap(ComponentPlacement.RELATED).addComponent(btnThem)
												.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnSua)
												.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnXoa)
												.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnLamMoi)
												.addPreferredGap(ComponentPlacement.RELATED).addComponent(btnThoiViec,
														GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(txtTenNV)
												.addGap(38).addComponent(jLabel6).addGap(18)
												.addComponent(txtCMND, GroupLayout.PREFERRED_SIZE, 224,
														GroupLayout.PREFERRED_SIZE)
												.addGap(18).addComponent(jLabel4)
												.addPreferredGap(ComponentPlacement.RELATED).addComponent(cbbGioiTinh,
														GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)))
						.addComponent(txtDiaChi, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE))
				.addGap(351)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
								.addComponent(txtTenNV, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(cbbTrangThai, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtCMND, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(cbbGioiTinh, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE).addComponent(
								txtMaNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
						.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(cbbLoaiNV, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
								.addComponent(txtSDT, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
								.addComponent(lableDiaChi, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(txtDiaChi, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
						.addGap(0, 77, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING,
								jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(btnThoiViec, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 50,
												Short.MAX_VALUE)
										.addComponent(btnLamMoi, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnXoa, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnSua, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnThem, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnTim, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnXoaRong, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
				.addContainerGap()));
		jPanel1.setLayout(jPanel1Layout);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		tableNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã nhân viên", "Tên nhân viên", "Giới tính", "SĐT", "Trạng thái", "Loại nhân viên", "CMND",
				"Địa chỉ" }));
		tableNhanVien.setRowHeight(30);
		tableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tableNhanVienMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tableNhanVien);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(jScrollPane1,
				GroupLayout.DEFAULT_SIZE, 1452, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(jScrollPane1,
				Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE));
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1456, Short.MAX_VALUE)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents
//    private void getQuanTheoThanhPho() {
//        vecQuanHuyen = daoDiaChi.getAllHuyenTheoTinh(cbbDCTinhTP.getSelectedItem().toString());
//        DefaultComboBoxModel<String> mdQuanHuyen = new DefaultComboBoxModel<>(vecQuanHuyen);
//        cbbDCQuanHuyen.setModel(mdQuanHuyen);
//    }
//
//    private void getPhuongXaTheoQuanHuyen() {
//        vecPhuongXa = daoDiaChi.getAllPhuongXaTheoTinhVaHuyen(cbbDCTinhTP.getSelectedItem().toString(), cbbDCQuanHuyen.getSelectedItem().toString());
//        DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
//        cbbDCPhuongXa.setModel(mdPhuong);
//    }

	private void loadDS() throws Exception {
		while (tableNhanVien.getRowCount() > 0) {
			modelNV.removeRow(0);
		}
		modelNV = (DefaultTableModel) tableNhanVien.getModel();
		for (NhanVien nv : daoNV.getDSNhanVien()) {
			modelNV.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.isGioiTinh() == true ? "Nam" : "Nữ",
					nv.getSdt(), nv.isTrangThaiLam() == true ? "Đang làm" : "Đã nghỉ",
					nv.isLoaiNhanVien() == true ? "Quản Lý" : "Nhân Viên", nv.getCmnd(), nv.getDiaChi() });
		}
	}

	private boolean regEx() {
		String ten = "^([A-ZĐÂÁƯ]{1}[a-zvxyỳọáầảấờễàạằệếýộậốũứĩõúữịỗìềểẩớặòùồợãụủíỹắẫựỉỏừỷởóéửỵẳẹèẽổẵẻỡơôưăêâđ]+)((\\s{1}[A-ZĐÂÁƯ][{1}a-vxyỳọáầảấờễàạằệếýộậốũứĩõúữịỗìềểẩớặòùồợãụủíỹắẫựỉỏừỷởóéửỵẳẹèẽổẵẻỡơôưăêâđ]*){1,})$";
		String ten2 = "^([A-ZĐÂÁƯ]{1}[A-ZVXYỲỌÁẦẢẤỜỄÀẠẰỆẾÝỘẬỐŨỨĨÕÚỮỊỖÌỀỂẨỚẶÒÙỒỢÃỤỦÍỸẮẪỰỈỎỪỶỞÓÉỬỴẲẸÈẼỔẴẺỠƠÔƯĂÊÂĐ]+)((\\s{1}[A-ZĐÂÁƯ][{1}A-VXYỲỌÁẦẢẤỜỄÀẠẰỆẾÝỘẬỐŨỨĨÕÚỮỊỖÌỀỂẨỚẶÒÙỒỢÃỤỦÍỸẮẪỰỈỎỪỶỞÓÉỬỴẲẸÈẼỔẴẺỠƠÔƯĂÊÂĐ]*){1,})$";
		String rgten = ten + "|" + ten2;
		String sdt = "^0[3|5|7|8|9]+[0-9]{8}$";
		String cmnd = "[0-9]{9}";

		if (!txtTenNV.getText().matches(rgten)) {
			JOptionPane.showMessageDialog(this, "Tên phải viết hoa chữ cái đầu tiên:\n" + "VD: Nguyễn Đình Thanh \n"
					+ "Hoặc viết hoa hết tất cả:\n" + "VD: NGUYỄN ĐÌNH THANH.");
			return false;
		}
		if (!txtSDT.getText().matches(sdt)) {
			JOptionPane.showMessageDialog(this, "Số điện thoại phải nhập đúng 10 chữ số!");
			return false;
		}
		if (!txtCMND.getText().matches(cmnd)) {
			JOptionPane.showMessageDialog(this, "CMND phải chứa đúng 9 chữ số!");
			return false;
		}
		if (txtDiaChi.getText().trim().equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ");
			return false;
		}
		return true;
	}

	private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbTrangThaiActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cbbTrangThaiActionPerformed

	private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaRongActionPerformed
		txtMaNV.setText("");
		txtTenNV.setText("");
		txtCMND.setText("");
		txtSDT.setText("");
		txtDiaChi.setText("");
	}// GEN-LAST:event_btnXoaRongActionPerformed

	private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimActionPerformed
		ArrayList<NhanVien> list = daoNV.timNVTheoTenVaSdt(txtTenNV.getText(), txtSDT.getText());
		if (true) {
			if (txtTenNV.getText().equals("") || txtSDT.equals("")) {
				JOptionPane.showMessageDialog(null, "Không được để trống hai trường Tên nhân viên và SĐT", "Warning",
						JOptionPane.WARNING_MESSAGE);
			} else if (list.size() == 0) {
				JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên", "Error", JOptionPane.ERROR_MESSAGE);
				txtTenNV.setText("");
				txtSDT.setText("");
				txtTenNV.requestFocus();
				return;
			}
			while (tableNhanVien.getRowCount() > 0) {
				modelNV.removeRow(0);
			}
			try {
				for (NhanVien nv : daoNV.timNVTheoTenVaSdt(txtTenNV.getText(), txtSDT.getText())) {
					modelNV.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.isGioiTinh() == true ? "Nam" : "Nữ",
							nv.getSdt(), nv.isTrangThaiLam() == true ? "Đang làm" : "Đã nghỉ",
							nv.isLoaiNhanVien() == true ? "Quản Lý" : "Nhân Viên", nv.getCmnd(), nv.getDiaChi() });
				}
			} catch (Exception ex) {
				Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
			}
		}

	}// GEN-LAST:event_btnTimActionPerformed

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
		// TODO add your handling code here:
		boolean loaiNV = cbbLoaiNV.getSelectedItem().toString().equalsIgnoreCase("Nhân viên") == true ? false : true;
		if (regEx()) {// regex
			int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm nhân viên ?", "Xác nhận",
					JOptionPane.YES_NO_OPTION);
			if (option == JOptionPane.YES_OPTION) {
				try {
					NhanVien nv = new NhanVien(daoNV.taoMaNgauNhienNhanVien(), txtTenNV.getText(),
							cbbGioiTinh.getSelectedItem().toString().equalsIgnoreCase("Nam"), txtSDT.getText(), "123",
							cbbTrangThai.getSelectedItem().toString().equalsIgnoreCase("Đang làm"), loaiNV,
							txtCMND.getText(), txtDiaChi.getText().trim());
					if (daoNV.timNhanVien(txtSDT.getText().trim()) == null) {
						daoNV.themNV(nv);
						JOptionPane.showMessageDialog(this, "Thêm thành công!");
						btnLamMoiActionPerformed(evt);
					} else {
						JOptionPane.showMessageDialog(this, "Thêm thất bại");
					}
				} catch (SQLException ex) {
					Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
				} catch (Exception ex) {
					Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
				}
			}

		}
	}// GEN-LAST:event_btnThemActionPerformed

	private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
		if (tableNhanVien.getSelectedRow() > -1) {
			if (regEx()) {
				int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa nhân viên ?", "Xác nhận",
						JOptionPane.YES_NO_OPTION);
				if (option == 0) {
					try {
						NhanVien nv1 = new NhanVien();
						nv1.setMaNV(txtMaNV.getText());
						nv1.setTenNV(txtTenNV.getText());
						nv1.setGioiTinh(cbbGioiTinh.getSelectedItem().toString().equalsIgnoreCase("Nam"));
						nv1.setSdt(txtSDT.getText());
						boolean trangThaiLam = cbbTrangThai.getSelectedItem().toString().trim() == "Đang làm" ? true
								: false;
						System.out.print("ttnv" + cbbTrangThai.getSelectedItem().toString());

						nv1.setTrangThaiLam(trangThaiLam);

						boolean loaiNV = cbbLoaiNV.getSelectedItem().toString() == "Quản Lý" ? true : false;
						System.out.print("loainv" + cbbLoaiNV.getSelectedItem().toString());
						nv1.setLoaiNhanVien(loaiNV);

						nv1.setCmnd(txtCMND.getText());
						nv1.setDiaChi(txtDiaChi.getText().trim());
						System.out.println(loaiNV);
						System.out.println(nv1);
						if (daoNV.capNhatNhanVien(nv1) > 0) {
							JOptionPane.showMessageDialog(this, "Sửa thành công!");
							btnLamMoiActionPerformed(evt);
						} else {
							JOptionPane.showMessageDialog(this, "Sửa thất bại");
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}

			}
		} else
			JOptionPane.showMessageDialog(this, "Nhân viên phải được chọn trên bảng!");
	}// GEN-LAST:event_btnSuaActionPerformed

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
		int row = tableNhanVien.getSelectedRow();
		if (row == -1) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên để xoá!");
		} else {
			String sdt = modelNV.getValueAt(row, 3).toString();
			int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá nhân viên? ", "Xác nhận",
					JOptionPane.YES_NO_OPTION);
			if (option == JOptionPane.YES_OPTION) {
				try {
					if (daoNV.xoaNhanVien(sdt.trim())) {
						System.out.println("IN");
						JOptionPane.showMessageDialog(this, "Xoá thành công!");
						btnLamMoiActionPerformed(evt);
					} else {
						JOptionPane.showMessageDialog(this, "Xoá thất bại!");
					}
				} catch (Exception ex) {
					Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		}

	}// GEN-LAST:event_btnXoaActionPerformed

	private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLamMoiActionPerformed
		try {
			loadDS();
		} catch (Exception ex) {
			Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btnLamMoiActionPerformed

	private void btnThoiViecActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoiViecActionPerformed
		int row = tableNhanVien.getSelectedRow();
		if (row > -1) {
			int option = JOptionPane.showConfirmDialog(this,
					"Bạn muốn cho nhân viên: " + modelNV.getValueAt(row, 1) + " thôi việc?", "Xác nhận",
					JOptionPane.YES_NO_OPTION);
			if (option == 0) {
				try {
					int kt = daoNV.capNhatNhanVienNghiLam(modelNV.getValueAt(row, 0).toString());
					if (kt > 0) {
						JOptionPane.showMessageDialog(this, "Thành công !");
					} else {
						JOptionPane.showMessageDialog(this, "Thất bại !");
					}
				} catch (Exception ex) {
					Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		}
	}// GEN-LAST:event_btnThoiViecActionPerformed

	private void tableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableNhanVienMouseClicked
		// TODO add your handling code here:
		int index = tableNhanVien.getSelectedRow();
		if (index != -1) {
			txtMaNV.setText(modelNV.getValueAt(index, 0).toString());
			txtTenNV.setText(modelNV.getValueAt(index, 1).toString());
			cbbGioiTinh.setSelectedItem(modelNV.getValueAt(index, 2));
			txtSDT.setText(modelNV.getValueAt(index, 3).toString());
			cbbTrangThai.setSelectedItem(modelNV.getValueAt(index, 4).toString());
			cbbLoaiNV.setSelectedItem(modelNV.getValueAt(index, 5).toString());
			txtCMND.setText(modelNV.getValueAt(index, 6).toString());
			txtDiaChi.setText(modelNV.getValueAt(index, 7).toString());
		}
	}// GEN-LAST:event_tableNhanVienMouseClicked

	private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaNVActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtMaNVActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLamMoi;
	private javax.swing.JButton btnSua;
	private javax.swing.JButton btnThem;
	private javax.swing.JButton btnThoiViec;
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnXoa;
	private javax.swing.JButton btnXoaRong;
	private javax.swing.JComboBox<String> cbbGioiTinh;
	private javax.swing.JComboBox<String> cbbLoaiNV;
	private javax.swing.JComboBox<String> cbbTrangThai;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel lableDiaChi;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableNhanVien;
	private javax.swing.JTextField txtCMND;
	private javax.swing.JTextField txtMaNV;
	private javax.swing.JTextField txtSDT;
	private javax.swing.JTextField txtTenNV;
	private JTextField txtDiaChi;
	// End of variables declaration//GEN-END:variables

}
