/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;


public class JPanel_ThemThuoc extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form TimKiem
     */
    public JPanel_ThemThuoc() {
    	setBackground(new Color(255, 255, 255));
        initComponents();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbuttonTimKiem = new javax.swing.JPanel();
        jPanelbuttonTimKiem.setBackground(new Color(255, 255, 255));
        btnThoat = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();

        btnThoat.setBackground(new Color(43, 123, 255));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new ImageIcon(JPanel_ThemThuoc.class.getResource("/image/icon/close_white.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new Color(43, 123, 255));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setIcon(new ImageIcon(JPanel_ThemThuoc.class.getResource("/image/icon/plus_white.png"))); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnXoaRong.setBackground(new Color(43, 123, 255));
        btnXoaRong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaRong.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaRong.setIcon(new ImageIcon(JPanel_ThemThuoc.class.getResource("/image/icon/close_white.png"))); // NOI18N
        btnXoaRong.setText("Xóa Rỗng");
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbuttonTimKiemLayout = new javax.swing.GroupLayout(jPanelbuttonTimKiem);
        jPanelbuttonTimKiemLayout.setHorizontalGroup(
        	jPanelbuttonTimKiemLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelbuttonTimKiemLayout.createSequentialGroup()
        			.addGap(454)
        			.addComponent(btnXoaRong)
        			.addGap(18)
        			.addComponent(btnXacNhan)
        			.addGap(18)
        			.addComponent(btnThoat, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(516, Short.MAX_VALUE))
        );
        jPanelbuttonTimKiemLayout.setVerticalGroup(
        	jPanelbuttonTimKiemLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanelbuttonTimKiemLayout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(jPanelbuttonTimKiemLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(btnThoat, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(jPanelbuttonTimKiemLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(btnXacNhan, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        					.addComponent(btnXoaRong, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE))))
        );
        jPanelbuttonTimKiem.setLayout(jPanelbuttonTimKiemLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanelbuttonTimKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanelbuttonTimKiem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(443, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaRongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaRongActionPerformed
    public void buttonThoat(ActionListener lis)
    {
        btnThoat.addActionListener(lis);
    }
    
    public void bttonXoaRong(ActionListener lis)
    {
        btnXoaRong.addActionListener(lis);
    }
    
    public void bttonXacNhan(ActionListener lis)
    {
        btnXacNhan.addActionListener(lis);
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JPanel jPanelbuttonTimKiem;
    // End of variables declaration//GEN-END:variables
}
